---
- name: Copy Configuration file for appfabric
  unarchive: 
    src: ../files/dist.zip 
    dest: /home/vagrant
    creates: no
    owner: vagrant 
    group: vagrant 
    mode: 0755

- command: npm install
  args:
    chdir: dist

- command: npm start
  args:
    chdir: dist    